### ISSUE TITLE
Blur in plasma widgets

### ISSUE THREAD

**Issue by robby81** [L4ki/Nord-Plasma-Themes#1]
Dear L4ki,

I read about plasma theme breeze now added blur on the transparent widgets. Do you also plan to do so?

**Comment by lazzaross** [comment]
Hi robby,

I'll do it.

But, I think it will be in Plasma 5.23, which comes out in October.

**Comment by L4ki** [comment]
Hi robby,

I'll do it.

But, I think it will be in Plasma 5.23, which comes out in October.

**Comment by robby81** [comment]
Hej,

you are probably right. I read about it and I am using the KDE git snapshots from openSUSE Tumbleweed, so I already saw it in breeze.

Thanks for all you work on the themes!
